services:
  server:
    hostname: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # env_file:
      # - .env
  client:
    hostname: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
